### PR TITLE
add dom helper

### PR DESCRIPTION
**Pull request by andresbott**
Add dom-helper script

wonderful.... no real change is done and yet we need to test the site ... 
URL for testing:

- https://dom-helper--website--fieitas.hlx.page/

### CODE REVIEW

**Comment by AlexRRR** [comment]
why are we getting 98% already?

**Comment by andreituicu** [comment]
Looks like the linter is complaining about indentation. Do you have an autoformater like prettier? might need to either deactivate it or play with the eslint configs to make it happy.

**Comment by andresbott** [comment]
I'm trying to get the linter to fix the 100 linting errors automatically ...

**Comment by AlexRRR** [comment]
remove scale change on hover, adjusted p margin.

**Pull request merged**
